name: Bug report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for helping improve Relay. Please fill out the sections below."
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How to reproduce the behavior
      placeholder: |
        1. Run `relay checkin`
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected
    validations:
      required: true
  - type: dropdown
    id: ide
    attributes:
      label: IDE / Environment
      options:
        - Cursor
        - VS Code
        - Claude Desktop
        - CLI only
        - Other
  - type: input
    id: version
    attributes:
      label: Relay version
      placeholder: e.g. 0.1.0 or commit hash
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      required: false
