name: Question
description: Ask a question about Relay
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: dropdown
    id: topic
    attributes:
      label: Topic
      options:
        - Setup / Installation
        - Cursor / MCP
        - VS Code
        - CLI
        - Jira / Integrations
        - Database / Schema
        - Other
